made custom button classes, restructured home page(no visual changes)
0xThresh/chainlink-spring-2023 pull request #21
Opened 2023-05-19 06:58 UTC by shobhitsundriyal

2023-05-22 08:22 UTC, Merdi-kim requested changes

2023-05-22 08:22 UTC, merdikim commented on frontend/src/pages/index.tsx
> +  const handleSignIn = async (userType: "agency" | "user") => {
You can revert these changes to what was there. Let's stick to links instead of buttons. The reason for that is because we shall handle wallet connect on the login screen instead of the landing page

2023-05-23 07:30 UTC, shobhitsundriyal commented on frontend/src/pages/index.tsx
> +  const handleSignIn = async (userType: "agency" | "user") => {
I think this would be better because it would better flow. Suppose user click on agency login and connects wallet, we can redirect to the dashboard if user is already registered else we can show the form. I mean why should we have separate login screen to connect wallet.

2023-05-23 09:22 UTC, Merdi-kim commented on frontend/src/pages/index.tsx
> +  const handleSignIn = async (userType: "agency" | "user") => {
The login screen is important because users must select which profile they want to log in with under their wallet. So a login page will serve them to do that

2023-05-24 04:26 UTC, shobhitsundriyal commented on frontend/src/pages/index.tsx
> +  const handleSignIn = async (userType: "agency" | "user") => {
But we will be able to display the lens profiles if the wallet is already connected, and we have the public address

2023-05-24 14:10 UTC, Merdi-kim commented on frontend/src/pages/index.tsx
> +  const handleSignIn = async (userType: "agency" | "user") => {
And in that case, how does a user choose which profile to use before going to the dashboard?

2023-06-05 10:53 UTC, Merdi-kim reviewed
LGTM

2023-06-05 10:53 UTC, merged